spring.application.name=shopflow
# H2 DATABASE
spring.datasource.url=jdbc:h2:mem:shopflow;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# SHOW SQL (optional but useful)
spring.jpa.show-sql=true

# H2 CONSOLE
spring.h2.console.enabled=true

# PORT
server.port=8081